name: 'sports_app_client'

services:
  react:
    container_name: react
    build:
      context: .
      target: production
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - "3000:80"
