version: '3.9'
name: 'sports_app_client'

services:
  react:
    container_name: react
    build:
      context: .
      target: production
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
