/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './router/__root'
import { Route as IndexImport } from './router/index'
import { Route as ViewUuidImport } from './router/view.$uuid'

// Create Virtual Routes

const WorkoutsLazyImport = createFileRoute('/workouts')()
const StatsLazyImport = createFileRoute('/stats')()
const SettingsLazyImport = createFileRoute('/settings')()

// Create/Update Routes

const WorkoutsLazyRoute = WorkoutsLazyImport.update({
  path: '/workouts',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./router/workouts.lazy').then((d) => d.Route))

const StatsLazyRoute = StatsLazyImport.update({
  path: '/stats',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./router/stats.lazy').then((d) => d.Route))

const SettingsLazyRoute = SettingsLazyImport.update({
  path: '/settings',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./router/settings.lazy').then((d) => d.Route))

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ViewUuidRoute = ViewUuidImport.update({
  path: '/view/$uuid',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsLazyImport
      parentRoute: typeof rootRoute
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsLazyImport
      parentRoute: typeof rootRoute
    }
    '/workouts': {
      id: '/workouts'
      path: '/workouts'
      fullPath: '/workouts'
      preLoaderRoute: typeof WorkoutsLazyImport
      parentRoute: typeof rootRoute
    }
    '/view/$uuid': {
      id: '/view/$uuid'
      path: '/view/$uuid'
      fullPath: '/view/$uuid'
      preLoaderRoute: typeof ViewUuidImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  SettingsLazyRoute,
  StatsLazyRoute,
  WorkoutsLazyRoute,
  ViewUuidRoute,
})

/* prettier-ignore-end */
