export const fullStatsLabels: Record<string, string> = {
	'max_heart_rate': 'max',
	'avg_heart_rate': 'avg',
	'max_speed': 'max',
	'avg_speed': 'avg',
	'enhanced_max_speed': 'max',
	'enhanced_avg_speed': 'avg',
	'max_power': 'max',
	'normalized_power': 'normalized',
	'avg_power': 'avg',
	'total_timer_time': 'move',
	'total_elapsed_time': 'elapse',
	'start_time': 'start',
	'end_time': 'end',
	'max_cadence': 'max',
	'avg_cadence': 'avg',
	'total_ascent': 'ascent',
	'total_descent': 'descent',
	'max_altitude': 'max',
	'min_altitude': 'min',
	'max_temperature': 'min',
	'avg_temperature': 'max',
	'total_strides': 'strides',
	'training_stress_score': 'TSS®',
	'total_calories': 'calories'
}
