name: cd
on:
  push:
    branches:
      - main
      - ci/cd


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          script: |
            cd ~/sports-app-frontend
            git pull
            git status
            docker compose up --build -d
