name: check
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: pnpm/action-setup@v4
      - name: install deps
        run: npm ci
      - name: lint
        run: npm run lint
