name: check
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9
      #      - name: install node
      #        uses: actions/setup-node@v4
      #        with:
      #          node-version: 22
      #          cache: 'pnpm'
      - name: install dependencies
        run: pnpm install

      - name: lint
        run: npm run lint
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9
      - name: install dependencies
        run: pnpm install

      - name: lint
        run: npm run test
